### PR TITLE
Add translation (Russian)

### PR DESCRIPTION
**Pull request by Igorrreha**
- [x] The commit message follows our guidelines.
- For bug fixes and features:
    - [x] You tested the changes.

**What kind of change does this PR introduce?**
This PR adds russian translation of lessons

**Does this PR introduce a breaking change?**
No
---

**Translation progress:**

Common files:
- [x] 1. application.po
- [x] 2. classref_database.po
- [x] 3. error_database.po
- [x] 4. glossary_database.po

Lessons:
- [x] 1. lesson-1-what-code-is-like.po
- [x] 2. lesson-2-your-first-error.po
- [x] 3. lesson-3-standing-on-shoulders-of-giants.po
- [x] 4. lesson-4-drawing-a-rectangle.po
- [x] 5. lesson-5-your-first-function.po
- [x] 6. lesson-6-multiple-function-parameters.po
- [x] 7. lesson-7-member-variables.po
- [x] 8. lesson-8-defining-variables.po
- [x] 9. lesson-9-adding-and-subtracting.po
- [x] 10. lesson-10-the-game-loop.po
- [x] 11. lesson-11-time-delta.po
- [x] 12. lesson-12-using-variables.po
- [x] 13. lesson-13-conditions.po
- [x] 14. lesson-14-multiplying.po
- [x] 15. lesson-15-modulo.po
- [x] 16. lesson-16-2d-vectors.po
- [x] 17. lesson-17-while-loops.po
- [x] 18. lesson-18-for-loops.po
- [x] 19. lesson-19-creating-arrays.po
- [x] 20. lesson-20-looping-over-arrays.po
- [x] 21. lesson-21-strings.po
- [x] 22. lesson-22-functions-return-values.po
- [x] 23. lesson-23-append-to-arrays.po
- [x] 24. lesson-24-access-array-indices.po
- [x] 25. lesson-25-creating-dictionaries.po
- [x] 26. lesson-26-looping-over-dictionaries.po
- [x] 27. lesson-27-value-types.po
- [x] 28. lesson-28-specifying-types.po

### CODE REVIEW

**Comment by PaulArgent** [comment]
Thank you @Igorrreha for joining the translation project! I really missed the proofreading. I As far as possible, I will do a detailed review.

**Comment by NathanLovato** [comment]
Hi there, thanks much for your contribution. I noticed reviewing the repository that this PR was seemingly completed, but I never got to review it as it was marked as draft. Could you confirm it's complete and ready to merge? If so, I'll fix the merge conflicts and integrate your translations into the repository.

**Comment by PaulArgent** [comment]
@NathanLovato I'd like to do a review before the merge, but if I don't find time in the next couple of weeks, you can merge. Then I will correct the inaccuracies in the new pull request when I find time for this.
We agreed with @Igorrreha that I will do a review, but I have a very busy schedule right now and I still can’t find time for this work. Sorry for that.

**Comment by NathanLovato** [comment]
I just merged and pushed manually ( see https://github.com/GDQuest/learn-gdscript-translations/commits/main ) to integrate the translations into the repository and be able to update the source translation strings.

The translations will be in the repo and should allow us to publish the Russian version of the app. You can then review them anytime. I think it's better to release new languages when possible and also get actual students to review and give feedback on the phrasing than keep waiting. You'll still be able to review and make improvements anytime.

Unfortunately, after syncing the strings, there'll be translations to check again. I wish we could rewrite the translation system, but we just have had way too much that is a much higher priority. We'll have much better foundations for that with the 4.0 remake of the app (using native web technologies).

**Pull request closed without merging**
