### PR TITLE
Add Spanish translation

### PR DESCRIPTION
**Pull request by NathanLovato**
Work in progress Spanish translation of the app.

### CODE REVIEW

**Comment by MetalMaxMX** [comment]
I'd like to add a tiny fix or modification from: https://github.com/GDQuest/learn-gdscript-translations/blob/09e4fb3671da2dc0f93770c79b4c8c15743fe4b4/es/lesson-1-what-code-is-like.po

So in line 203-205 there's this sentence ""Es un lenguaje excelente para iniciarse en la programación porque es "
"especializado. A diferencia de otros lenguajes, no tiene una cantidad "
"abrumadora de funcionalidades que tengas que aprender.\n"" 

I'd personally go with "A diferencia de otros lenguajes, **este** no tiene una cantidad abrumadora" to show that it is referring to the language itself. Of course a casual reader may gleam from context that it is speaking about the language itself but I'd rather have it this way to be a little bit more clear on intent. 

And in line 408 ""Hablando de eso, ¡es hora de ver la pantalla de práctica!\n"", shouldn't be "¡**E**s hora de ver la pantalla de práctica!" since you're starting a sentence with ¡ so the first letter should be in caps to my knowledge. 

Feel free to correct me if I'm wrong on this though. This was just intuition or me feeling something off.

**Comment by NathanLovato** [comment]
I'll send this to the translator to check.

**Comment by NathanLovato** [comment]
Regarding exclamation in the middle of a sentence, without a capital letter, see this explanation from the Real Academía Española, it's correct: https://www.rae.es/dpd/interrogaci%C3%B3n

**Comment by MetalMaxMX** [comment]
Ah, all right then! Always thought you should always capitalize, good to know it isn't necessarily true. I do stand by the other modification I mentioned though

**Comment by NathanLovato** [comment]
> I do stand by the other modification I mentioned though

It's unnecessary unless actual users in the target audience struggle to read in practice. It's a sentence with only subject, there's no ambiguity to clear

**Comment by MetalMaxMX** [comment]
Yeah, I was just thinking that it could be a correction on first glance but now that I take a look at it, there aren't any other subjects it can refer so should be left as is.

**Pull request merged**
