### PR TITLE
Add German translations

### PR DESCRIPTION
**Pull request by SpeCter**
### Overview:

**(mostly) completed:**
- [x] Lesson 1
- [x] Lesson 2
- [x] Lesson 3
- [x] Lesson 4
- [x] Lesson 5
- [x] Lesson 6
- [x] Lesson 7
- [x] Lesson 8
- [x] Lesson 9
- [x] Lesson 10
- [x] Lesson 11
- [x] Lesson 12
- [x] Lesson 13
- [x] Lesson 14
- [x] Lesson 15
- [x] Lesson 16
- [x] Lesson 17
- [x] Lesson 18
- [x] Lesson 19
- [x] Lesson 20
- [x] * application (= Lesson 28)
- [x] * classref (= Lesson 28)
- [x] * error_database (= Lesson 28)

**machine translated only:**
- [ ] Lesson 21
- [ ] Lesson 22
- [ ] Lesson 23
- [ ] Lesson 24
- [ ] Lesson 25
- [ ] Lesson 26
- [ ] Lesson 27
- [ ] Lesson 28
- [ ] * glossary_database

**not done/started:**

 ** Needs updates for new lessons when they arrive, see comment in parenthesis for current status

### CODE REVIEW

**Comment by SpeCter** [comment]
Lesson 1-20 completely translated now

**Comment by SpeCter** [comment]
Added Lesson 21 - 28 machine translation
Added glossary_database machine translating
Updated and translated classref_database

**Comment by NathanLovato** [comment]
@SpeCter may I merge this PR so that the translated lessons appear in Weblate? Contributors can now collaborate on translations on the same platform Godot uses.

**Comment by SpeCter** [comment]
Sure, go ahead

**Comment by SantosSi** [comment]
> @SpeCter may I merge this PR so that the translated lessons appear in Weblate? Contributors can now collaborate on translations on the same platform Godot uses.

If the German translation was synched with Weblate, is the warning there (copied into here below) counterproductive and causes translators to refrain from continuously translating?

> The [German translation](https://github.com/GDQuest/learn-gdscript-translations/pull/2) in particular is almost complete, so if you contribute to German on Weblate, your work will be lost.

**Pull request merged**
