### PR TITLE
Add Italian translation

### PR DESCRIPTION
**Pull request by DjMike238**
This is still a WIP.

- [ ] `application`
- [ ] `classref_database`
- [ ] `error_database`
- [ ] `lesson-1` (100% complete, needs proofreading)
- [ ] `lesson-2` (100% complete, needs proofreading)
- [ ] `lesson-3` (100% complete, needs proofreading)
- [ ] `lesson-4`
- [ ] `lesson-5` (45% complete)
- [ ] `lesson-6`
- [ ] `lesson-7`
- [ ] `lesson-8`
- [ ] `lesson-9`
- [ ] `lesson-10`
- [ ] `lesson-11`
- [ ] `lesson-12`
- [ ] `lesson-13`
- [ ] `lesson-14`
- [ ] `lesson-15`
- [ ] `lesson-16`
- [ ] `lesson-17`
- [ ] `lesson-18`
- [ ] `lesson-19`
- [ ] `lesson-20`

### CODE REVIEW

**Comment by NathanLovato** [comment]
Thanks much for contributing the Italian version :)

**Comment by NathanLovato** [comment]
Are you actively working on this right now or should I merge what you translated already? 

People can now translate using the Weblate online service, but to synchronize with the available translations with Weblate, we need to merge them in the repository.

Note that if we merge now you would be able to use weblate to continue translating if you would like.

https://hosted.weblate.org/projects/learn-gdscript-from-zero/

**Comment by DjMike238** [comment]
> Are you actively working on this right now or should I merge what you translated already? 

As you probably saw, we had some stuff that we didn't push until a few minutes ago, so now you can merge the translation just fine!

Anyway, is it fine if we keep updating the progress on this PR's first message?

**Comment by NathanLovato** [comment]
> Anyway, is it fine if we keep updating the progress on this PR's first message?

Absolutely! I also posted a warning on Weblate that people should check PRs to not waste time on things already translated in a PR.

**Comment by kagenash1** [comment]
I'd like to help with this, though I don't see the italian version in Weblate

**Comment by NathanLovato** [comment]
Gonna merge what you did already to sync translations on weblate and allow people to contribute there. I'll let you all coordinate to see how you want to continue translations.

**Pull request merged**
